--q16
SELECT E.Ssn, P.Name, SUM(S.Hours) AS TotalHours
FROM PERSON P
JOIN EMPLOYEE E ON P.Ssn = E.Ssn
JOIN MAINTAINS M ON E.Ssn = M.Ssn
JOIN [SERVICE] S ON M.SERVICE_ID = S.SERVICE_ID
JOIN PLANE_SERVICE PS ON S.SERVICE_ID = PS.SERVICE_ID
JOIN OWNS O ON PS.Reg# = O.Reg#
WHERE O.Ssn IN (
    SELECT Ssn
    FROM PERSON
    WHERE Name = 'ABC Inc.' AND Category = 'Corporation'
)
GROUP BY E.Ssn, P.Name
ORDER BY TotalHours DESC;