--q18
SELECT DISTINCT P.[Name], P.[Address]
FROM PERSON P
INNER JOIN OWNS O ON P.Ssn = O.Ssn
INNER JOIN AIRPLANE A ON O.Reg# = A.Reg#
INNER JOIN PLANE_TYPE PT ON A.OF_TYPE = PT.Model
WHERE P.Category = 'Individual'
AND PT.Model IN (
SELECT PT2.Model
FROM PLANE_TYPE PT2
INNER JOIN AIRPLANE A2 ON PT2.Model = A2.OF_TYPE
INNER JOIN OWNS O2 ON A2.Reg# = O2.Reg#
INNER JOIN PERSON P2 ON O2.Ssn = P2.Ssn
WHERE P2.Category = 'Corporation'
AND O2.Pdate >= DATEADD(MONTH, -1, GETDATE())
);
